flatcar/nebraska

- Dockerfile.nebraska
The build system requires bash, so install it.
> build: Fix build of nebraska docker image

- pkg/api/updates.go
- pkg/api/updates_test.go
Here is my "knee-jerk reaction" fix for #76. All the existing tests seem to pass, but probably some other test is needed, but for that I would like to know what behaviour is actually desired. There is obviously a problem that there is no explanation what this temporary hack was supposed to work around, which leaves me wondering what kind of workflow this change is going to break…
Fixes #76.
> backend: Repeat the info about available update if the client asks about it again for the same app

- go.mod
- go.sum
- pkg/api/activity_test.go
- pkg/api/applications_test.go
- pkg/api/channels_test.go
- pkg/api/events_test.go
- pkg/api/groups_test.go
- pkg/api/instances.go
- pkg/api/instances_test.go
- pkg/api/packages_test.go
- pkg/api/updates_test.go
- pkg/omaha/omaha.go
- pkg/syncer/syncer.go
github.com/satori/go.uuid haven't seen code changes for over a year
now. This normally wouldn't be a problem if not for the fact that the
library apparently has some issues with generation of the random
UUIDs. Also the top issue in the repository has a title "PSA: This
repo is dead".
Alternatives were github.com/gofrs/uuid or github.com/google/uuid. The
former seems to be a continuation of the satori's repo. Picked the
latter, since I wasn't sure about the longevity of the former.
We still require the repository indirectly, though. When we replace
the ORM we have now with something else, then the old UUID package
will likely go away.
> backend: Migrate to a maintained uuid package

- pkg/omaha/omaha.go
- pkg/syncer/syncer.go
It maybe possible that the app response will not contain the update
check element, so after decoding the update check field in the struct
may be nil. If that happens, treat it as no update available.
> backend: Fix nil pointer dereference in syncer

- pkg/api/instances.go
- pkg/api/instances_test.go
Currently syncer sends requests with machine ID set to something like
'{8d180b2a-0734-4406-af02-9a4f86bd1ee0}', while update_engine uses
contents of /etc/machine_id, which are in form like
'8d180b2a07344406af029a4f86bd1ee0'.
> backend: Temporarily filter out instances with bracketed IDs

- pkg/api/activity.go
- pkg/api/activity_test.go
- pkg/api/applications.go
- pkg/api/applications_test.go
- pkg/api/groups.go
- pkg/api/groups_test.go
- pkg/api/instances.go
- pkg/api/metrics.go
This is to avoid skews in statistics or metrics resulting from taking
fake instances into account.
> backend: Ignore instances with bracketed IDs in more places

- frontend/src/js/api/API.js
- frontend/src/js/components/Instances/List.js
- frontend/src/js/stores/InstancesStore.js
Due to #122 the instances list view was displaying just up to 500 instances.
This patch fixes that until we have the backend pagination working correctly.
> Show correct number of instances in instances list view

- cmd/nebraska/auth/githubauth.go
- cmd/nebraska/nebraska.go
- docs/authorization.md
If the flag `-gh-enterprise-url` is specified, use that as endpoint for
GitHub authentication following the GitHub Enterprise conventions.
> auth/github: support GitHub Enterprise

- cmd/nebraska/controller.go
- cmd/nebraska/controller_test.go
- cmd/nebraska/nebraska.go
- frontend/src/js/api/API.js
- frontend/src/js/components/Header.react.js
This PR allows us to set the access management URL according to the auth backend being used, i.e. fixes #130 and makes it more future-proof when we add more authentication backends.
> Fix access management URL

- docs/authorization.md
`authentication)` is currently off in a new line below the header.
> docs/authorization: fix header markdown

- cmd/nebraska/nebraska.go
You should be able to configure the Github client ID for Github authorization by setting the environment variable: `NEBRASKA_GITHUB_OAUTH_CLIENT_ID`. However, `nebraska` isn't picking up the value of this env var. Instead, when you set it, `nebraska` fails to start with this error message:
```
{"_t":"2020-03-03T06:47:12+0000", "_p":"1", "_l":"ERR", "_n":"nebraska", "_m":"no oauth client ID"}
```
The bug is in `func obtainOAuthClientID`. There's a check for empty string that is looking at the wrong variable. That's fixed in this PR.
(I glanced through the other `obtain*` functions to see if they had similar issues. They all look good. It's only `obtainOAuthClientID` that has this issue.)
> Fix reading NEBRASKA_GITHUB_OAUTH_CLIENT_ID env var.

- frontend/src/js/components/Channels/Item.react.js
- frontend/src/js/components/Channels/List.react.js
This PR addresses the problem of having the channel list too clutter due to having new architectures and the same channels' names.
For being able to scale a bit better maybe we should have the architectures as tabs in the future, but this is a good and quick improvement for now.
**Old:**
**New:**
> Restyle channels list

- frontend/built/index.html
The CSS files were removed with acf65f9a5bd15bb1d9811fac9295eb0fac20b1b2
when switching to the new Material UI and are not needed & available
anymore.
> frontend: remove obsolete CSS links from index.html

- frontend/src/js/components/Channels/EditDialog.js
The package name and createdAt field seem to arise in the same line which lead to bad user experience
made the createdAt field the secondary text for each package Item.
fixes #132
> Frontend : Fixed visual clutter for package select

- docs/authorization.md
The documentation about running a database for development was still
using the container built by CoreRoller (and with the name updated to
Nebraska by mistake).
Instead of relying on a dedicated container for the database, we should
just provide the instructions to quickly set it up for Nebraska. So
these changes replace the mentioned legacy instructions this way.
> docs: Update/fix the recommended way of running the database

- Dockerfile.nebraska
- Makefile
Closes #129.
This PR follows up the #129 PR by making the changes as suggested there.
I had some more changes with regard to tools, but those I'll put in a separate PR when it's ready.
> Enable goproxy and run no linters inside container build

- cmd/nebraska/controller.go
- cmd/nebraska/nebraska.go
- frontend/src/js/api/API.js
- frontend/src/js/components/Applications/ApplicationItemGroupItem.react.js
- frontend/src/js/components/Groups/Charts.js
- frontend/src/js/components/Groups/Item.react.js
- frontend/src/js/components/Groups/ItemExtended.react.js
- frontend/src/js/components/Instances/List.js
- frontend/src/js/constants/helpers.js
- pkg/api/api.go
- pkg/api/groups.go
- pkg/api/groups_test.go
- pkg/api/updates_test.go
This PR decouples fetching the version breakdown + the instances stats from when getting a group's information.
Those queries were done in order to make it simpler for the UI to show the info, but they're a bit heavy so we should avoid them when they're not needed.
The PR also adds connections limits to the DB (overridable by the use of env vars).
> Make queries slimmer

- frontend/src/js/__tests__/Common/EmptyContent.spec.js
- frontend/src/js/__tests__/Common/__snapshots__/EmptyContent.spec.js.snap
- frontend/src/js/components/Common/EmptyContent.js
Instead of checking the EmptyContent's children types and wrap them in
a Typography element or add them directly, we should just wrap all the
children in a Typography element, since the contents of EmptyContent
are supposed to be textual anyway.
> frontend: Simplify EmptyContent

- pkg/api/updates.go
- pkg/api/updates_test.go
When there are timed-out instances which didn't complete their update
and their number reaches the number of maximal allowed updating
instances, updates will be disabled in Safe Mode. However, this was
also the case when Safe Mode is not used, causing updates to be
disabled permanently when enough clients don't ping back due to
failures or when malicious clients are making many requests exceeding
the number of maximal allowed updating instances (Such a DoS is
unfortunate and we can't do something about it but it shouldn't result
in updates being disabled permanently).
Just limiting the disabling of updates to the Safe Mode is not enough
because ErrMaxTimedOutUpdatesLimitReached would still be reached for
all future update requests. Therefore, disabling updates and returning …
> backend: Disable/disallow updates after timeout only in Safe Mode

- pkg/api/api.go
- pkg/api/applications.go
- pkg/api/channels.go
- pkg/api/events.go
- pkg/api/instances.go
- pkg/api/packages.go
- pkg/api/updates.go
Errors like those reported from the database library went unnoticed
because there was no error logging in the API package.
Log all errors with enough context to relate them to request errors
when the original errors are turned into other errors for the client.
> backend: Add error logging for API package

- pkg/api/groups.go
- pkg/api/groups_test.go
SQL errors like the following led to no updates being served at least a
couple of times when I tested it:
GetUpdatePackage - getGroupUpdatesStats error (propagates as
ErrGetUpdatesStatsFailed): sql: Scan error on column index 1, name
"updates_to_current_version_granted": converting NULL to int is
unsupported
Covers the case when no row exists by defaulting to 0 as value.
> backend: Fix type for UpdatesStats

- frontend/src/js/components/Header.react.js
We were passing the mentioned config to the useStyles function of the
Appbar component and this was causing an issue when the config was null.
Passing the config was left over as a mistake, so this patch simply
removes it.
> frontend: Don't pass the cacheConfig to the Appbar's useStyles function

- Makefile
- tools/run-all.sh
- tools/run-local-nebraska.sh
- tools/setup_local_db.sh
There was no straightforward way of running the local database and nebraska since dockerfile.postgres was removed. So I've added 3 scripts - one for setting up the database (which the build system is now using), one for running a local no-auth nebraska instance, and one that does both of the above and a proper cleanup. Now checking if some thing works (during a PR review, for example) should basically be `git checkout …; make; ./tools/run-all.sh` and going to `localhost:8000` in a browser.
I used that to review #250.
> Add scripts for easy running of local instances of the database and nebraska

- frontend/package-lock.json
- frontend/package.json
This fixes a low-severity security issue related to the node-fetch
dependency of the mentioned package.
> frontend: Update "formik" package to 2.1.5

- cmd/nebraska/controller.go
- cmd/nebraska/nebraska.go
- pkg/syncer/syncer.go
- pkg/syncer/syncer: Add parameters for sync interval and source URL
The interval was hardcoded to one hour which is inconvenient when new
settings should be quickly propagated during a test phase. The sync
URL was also hardcoded and required source code changes when a different
source URL should has to be used.
Expose both values as parameters with the current values as default.
- pkg/syncer/syncer: Reduce waiting time between two channels
The syncer was sleeping for a minute before the next channel was
synced. This makes it look like a bug and even if known it is not
really useful but rather disturbing to wait 8 minutes until all
channels are synced.
Wait for 5 seconds which is a bit waiting time to not hammer the
server but still allows to sync all channels in under a minute.
> Syncer configuration

- pkg/syncer/syncer.go
The LTS channels for the different streams should be synced but not the
placeholder LTS channel used to manage the desired version in Nebraska.
Extend teh list of hard-coded synced channels with those that start
with "lts-" denoting an LTS stream channel. Ideally this would be a
boolean field on the channel itself, to set whether to sync or not.
> pkg/syncer/syncer: Extend list of synced channels with LTS

- README.md
Kinvolk now has a Contribution repository with a Code of Conduct as well
as PR/commit guidelines, so we mention them in the README.
> README: Add CoC and commit guidelines

- Makefile
`go build -trimpath` removes the full path info used in the build
process of the binary. (less info for folks to sniff out)
Signed-off-by: Vincent Batts <vbatts@kinvolk.io>
for reference
> Makefile: build nebraska without host path info

- go.mod
- go.sum
To address
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-14040.
To verify that this version will be used, run:
"go list -m golang.org/x/text".
You should see the following output:
"golang.org/x/text v0.3.4"
Signed-off-by: Mateusz Gozdek <mateusz@kinvolk.io>
> go.mod: update golang.org/x/test to v0.3.4

- pkg/api/api.go
regardless of the hosts' umask, there is an occassional difference in
the mode of the generated bindata content (0644 vs 0664).
Just instruct the generated output to be 0644.
Signed-off-by: Vincent Batts <vbatts@kinvolk.io>
> pkg/api: force the mode on go-bindata

- frontend/src/js/components/Groups/EditDialog.js
Currently we were using the Switch component from formik-material-ui
which was sending switch values wrapped in array and there was no
way to change this behaviour. We already have material-ui as a
dependency and thus it makes sense to use the Switch component directly
from there which also returns by default boolean values for Switch.
fixes #298
> Fix Group creation

- pkg/api/activity.go
- pkg/api/activity_test.go
- pkg/api/groups_test.go
- pkg/api/instances.go
- pkg/api/updates.go
- pkg/api/updates_test.go
This PR has the following optimizations affecting the `GetUpdatePackage` method:
* When updating the instance status, update `instance` + `instance_application` in the same query (instead of 2 queries);
* Don't update the `instance_application` twice when granting an update (it was setting the version + timestamp, etc. and then updating the status) which means 1 write instead of 2;
* Don't update the `instance_application` when an instance checks in if the last check in is less than 5 minutes ago (this reduces drastically the number of constant writes when using the `updateservicectl` fake instances which constantly ping the server)
* Don't fetch the group's stats (it's a count query that may get complex if we have lots of instances registered in the last 24h) unless we need them for …
> Optimize update instance status

- cmd/nebraska/nebraska.go
Private instances that are deployed on the Internet should sometimes
only serve a set of trusted clients. Since the server interacts with
human users via the administration web interface, an IP address filter
on the host system is not convenient.
Allow to move the Omaha API endpoint to a secret path so that only
clients that know the path are able to register. The secret is appended
to the well-known /v1/update path and separated by a slash. For now
there is only one global secret specified as program parameter.
A future feature could be to manage multiple secrets in the web UI
conveniently to handle leaks, transitions, and multiple trustees.
```
make backend-binary
docker run --rm -d --name nebraska-postgres-dev --tmpfs /var/lib/postgresql/data:rw,noexec,nosuid,size=5G --network host -e …
```
> cmd/nebraska: Support secret API endpoint suffix for private instances

- frontend/src/js/constants/helpers.js
The instances' details view was showing the date of the last update
check without the month information, regardless of whether we were in
the same month currently as the date in question. This patch fixes that
by showing the full numeric date. We can add a more human-friendly date
format later if needed.
fixes #299
> frontend: Show the full date in the instance details view

- cmd/nebraska/controller.go
- cmd/nebraska/nebraska.go
- frontend/src/js/api/API.js
- frontend/src/js/components/Instances/Details.js
- frontend/src/js/components/Instances/Item.react.js
- frontend/src/js/components/Instances/Table.js
- frontend/src/js/components/Layouts/InstanceLayout.js
- go.mod
- go.sum
- pkg/api/activity_test.go
- pkg/api/applications_test.go
- pkg/api/bindata.go
- pkg/api/db/migrations/0010_add_instance_alias.sql
- pkg/api/events_test.go
- pkg/api/groups_test.go
- pkg/api/instances.go
- pkg/api/instances_test.go
- pkg/api/updates.go
- pkg/api/updates_test.go
- pkg/omaha/omaha.go
We want users to be able to rename instances in order to more easily identify them.
This PR adds a new `alias` column to the instance table, the respective update endpoint, and the UI changes.
> Add instance alias

- pkg/api/events.go
- pkg/api/instances.go
The Complete event is sometimes ignored similarly to unexpected events
when no update is in progress. This is supposed to prevent Complete
events for already updated instances or those where the previous
version mismatched the version seen by the server. However, the
previous version seen by the server is nothing to be trusted because
the database state may be wrong or from a malicious client. Since
update-engine has inbuilt rollback detection it will create an error
event on its own if it detects that it does not run the new version
instead of a Complete event. The case left to cover is that
update-engine sends Complete events all the time in normal operation
and we want to reset the updating state so that the instance can be
granted updates again. Therefore, do a state transition even …
> backend: Ensure instances are not stuck in an updating state

- pkg/api/events.go
The group's stats take a while to fetch, and they were being fetched
only to be used solely if the "disableUpdatesOnFailedRollout" is true.
So the group's stats should rather be gathered only if the mentioned
setting is true which is much quicker to check, and moreover, this
setting is only true during the tests.
This patch thus switches the order of fetching the group's stats +
checking the mentioned setting, which should make things faster.
> backend: Don't fetch group stats in events unless it's really needed

- pkg/api/applications.go
- pkg/api/bindata.go
- pkg/api/channels.go
- pkg/api/db/migrations/0011_add_index_instance_application.sql
- pkg/api/groups.go
- pkg/api/instances.go
From the RDS performance insights, the query on instance_application table is slow. The composite index and removal of extra query parameters will boost the performance. See the attached pictures for the difference in query planner.
Query: 
---
SELECT "version", "status", "last_check_for_updates", "last_update_version", "update_in_progress", "application_id", "group_id" FROM "instance_application" WHERE (("instance_id" = ?) AND ("application_id" = ?) AND last_check_for_updates > now() at time zone ? - interval ? AND (instance_id IS NULL OR instance_id NOT SIMILAR TO ?))
Before composite index
After composite index
---
> Optimisations for slow queries in instance_application table

- pkg/api/bindata.go
- pkg/api/db/migrations/0013_add_stats_indexes.sql
- pkg/api/groups.go
1. Index: `instance_application_group_id_last_check_for_updates_instan_idx`
Improves the performance of GetGroupInstancesStats. Earlier the query goes through a `sequential scan`.
Before:
After:
Improvement `1s698ms` to `98ms`
2. `GetGroupVersionCountTimeline` is broken down into two queries.
The IN operator in the query is costly and performance varies based on the number of recent_instances. 
Refer: https://www.datadoghq.com/blog/100x-faster-postgres-performance-by-changing-1-line/
Old query: 16m23s
New: 2m50s (query 1: 3s393s+query 1: 2m47s)
Note: The performance improvement increases exponentially with the increase in the number of recent instances
> Optimise performance of analytics queries

- cmd/nebraska/controller.go
- pkg/api/groups.go
- pkg/api/groups_test.go
A cache layer for Group Version Count Timeline is added
with cache life span of 1 minute.
Signed-off-by: yolossn <santhosh@kinvolk.io>
> backend: Cache Group Version Count Timeline

- cmd/nebraska/controller.go
We have the noop auth backend which has no session set, and due to the
recent changes to set the user in the log context, it was failing.
> backend: Do not fail when trying to log without a session

- charts/nebraska/Chart.yaml
- charts/nebraska/templates/update-ingress.yaml
- charts/nebraska/values.yaml
Optionally add an extra ingress handling paths /v1/update and /flatcar,
allowing different whitelisting options to the user interface and the
update endpoints.
Enable extra ingress and set different annotations. Example `values.yaml` snippet:
```
ingress:
enabled: true
annotations:
nginx.ingress.kubernetes.io/whitelist-source-range: 172.23.68.21
update:
enabled: true
annotations: {}
```
Web interface is only accessible from `172.23.68.21`, flatcar nodes from anywhere can be upgraded.
> chart: Add option for separate /v1/update and /flatcar ingress

- docs/managing-updates.md
- docs: document how to set a machine alias    
The machine alias is a recent Nebraska feature which wasn't documented
yet.
-    docs: Use Container Linux Config in example   
The cloud-init cloud config example should not be prominent because
Container Linux Config (Ignition) is the recommended way for
provisioning. Since both are YAML it's confusing to mention the
cloud-init format in the example.
> docs: Container Linux Config examples

- frontend/src/js/components/Header.tsx
The frontend was trying to parse an empty string if the client config
was not yet stored locally, and this resulted in an error.
Effectively, this prevented getting the UI when accessing Nebraska for
the first time (in whatever the deployment URL was).
> frontend: Prevent issue when the client config is not stored

- frontend/src/js/components/Instances/Charts.tsx
We don't want to show any label on instance status pie chart, the
correct way to not render any label is to pass a component to labels
prop which renders null.
Yes
> frontend: Fix labels for instance status area chart

- backend/tools/check_pkg_test.sh
mapfile is not in older bash versions, so check_pkg_test.sh does not work.
On Mac for example, bash 5 can be installed but not as /bin/bash. /bin/bash is the ye-olde-system version of bash that does not support mapfile. This PR fix allows people who have a newer version of bash installed have `make` work. 
---
ps. An alternative to this PR would be to rewrite check_pkg_test.sh to not use mapfile... but if we're going to make it more portable, maybe it would be better to redo it in go or node? So instead of doing either of those, this PR/quick-fix at least makes it work on mac(and alt-shell users) for people who have bash 5 installed.
> backend: Fix check_pkg_test.sh script to use env bash

- charts/nebraska/templates/deployment.yaml
This changes changes the order of if-else statements in the deployment, making `.Values.config.hostFlatcarPackages.nebraskaURL` have precedence over the values generated from `.Values.ingress`
For our use case, this allows us to specify a `https` url rather than a `http` url, as our ingress controller implicitly adds and forces TLS, even when not specifying `spec.tls` in the `Ingress` resource. Another use case could be different internal and external hostnames when using a load balancer.
Specify values of `ingress.enabled: true` and `config.hostFlatcarPackages.nebraskaURL: <some valid url>`. The specified URL now will be templated into the `Deployment` resource as the argument to `-nebraska-url`.
Using a values-file containing the following and more:
```
config:
hostFlatcarPackages: …
```
> chart: allow overriding the nebraska-url argument

- .github/workflows/frontend.yml
Removes the older unsupported node version, and adds the LTS and the current (16 future LTS) node version for testing.
Additionally it changes the Ubuntu version to run the tests under to the current LTS version (20.4).
So we test the previous node LTS (12), the current LTS(14), and the future LTS (16 to see if our libraries work there).
This changes what is tested on CI.
> Update frontend github workflow node (LTS, current) and Ubuntu LTS

- frontend/src/js/components/Groups/Item.tsx
- frontend/src/js/components/Groups/ItemExtended.tsx
- frontend: Fix type of argument in Group/Item's translation
- frontend: Share the format for rate policy in Groups/Item|ItemExtended
- frontend: Inform the user of unlimited updates in the update policy
> Humanize policy numbers

- frontend/src/js/components/Header.tsx
Otherwise we see the empty space before the "Manage Account" menu,
which looks bad.
> frontend: Show email/name row in account menu only if they exist

- Makefile
Some targets were not updated when the backend code was moved into the
backend/ directory, and it was passing the CI tests still because the
diff that triggers the CI testing was running against files that did
not exist.
> Makefile: Ensure the test targets are run from the backend dir

- backend/pkg/api/instances.go
- backend/pkg/api/instances_test.go
By default the sortFilter is found in the instance app table and when
mapping instanceApplications to instance we were not applying the
filters, this lead to wrong list of instances to be shown in the UI.
[ describe what reviewers need to do in order to validate this PR ]
Go to the instance list view apply the filters and you will see the correct list with filters getting applied 
YES
fixes #426
> backend: Fix instance list filtering when filtered by status & version

- Dockerfile
- Makefile
- Makefile: Allow to override the version label
- build: Set the version from the original source instead of the container
> version from source

- frontend/src/js/components/Instances/Charts.tsx
Set the tooltip only when the tooltip boolean is not turned on
Go to the GroupExtended View and hover over InstanceStatusArea Charts quickly jump from one chart to other and the tooltip would not remain persistent.
fixes #424
> frontend: Fix persistent chart tooltip 

- Makefile
- backend/pkg/api/events.go
- backend/pkg/api/events_test.go
We had a [limit](https://github.com/kinvolk/nebraska/blob/main/backend/pkg/api/events.go#L167) on how we consider an update to be done because we were only contemplating how Flatcar behaves.
Yet, as far as understand from the [protocol](https://github.com/google/omaha/blob/master/doc/ServerProtocolV3.md), there are [3 different ways](https://pkg.go.dev/github.com/kinvolk/go-omaha/omaha#EventResult) to represent success and we should definitely consider them.
**Update:** Turns out the event types are stored in the DB and I don't want to add a migration to include the ResultSuccessRestartBrowser case, so I dropped support for this event result type. I could add a hack where I always query the ResultSuccess if there's ResultSuccessRestartBrowser, but I don't think it's worth it and instead …
> Allow other result success cases to complete the update

- Makefile
- backend/pkg/api/activity.go
- backend/pkg/api/events_test.go
- backend/pkg/api/groups_test.go
- Makefile: Make it easier to get the code coverage report
- tests: Cover testing Group's track name
- tests: Cover the corner-case of Flatcar instances reporting 0.0.0.0
- tests: Cover GetEvent
> Increase test coverage

- backend/pkg/api/groups.go
- backend/pkg/api/updates_test.go
- groups: Replace GetGroupInstancesStats's query by goqu
- backend: Count up to date instances without history as complete
> Clarify up to date instances' status

- frontend/src/js/components/Groups/EditDialog/GroupDetailsForm.tsx
The group's track is more important than the group's description and
it's easy to miss as it is the last field in the form. So this patch
simply moves it above the description in the creation/edition form.
> frontend: Move the group's track above the description in edit form

- updater/updater_example_test.go
- updater/updater_example_with_update_handler_test.go
I made the tests part of the updater package when I stopped exporting the NewUpdateInfo method but still needed to test it.
However, I mistakenly made the example tests also part of the updater package, and those should indeed be black box style.
This commit fixes that.
> Updater example tests blackbox

- charts/nebraska/Chart.yaml
- charts/nebraska/templates/deployment.yaml
- charts/nebraska/values.yaml
To specify how many old ReplicaSets for the Deployment user want to
retain, adding this field. Default is 10 if the field is removed.
closes: #494
Signed-off-by: knrt10 <kautilya@kinvolk.io>
> Add field revisionHistoryLimit to deployment

- backend/pkg/api/activity.go
- backend/pkg/api/instances.go
Some DB API usage fixes that could potentially fix some db connection leaks.
This tries to be a bit more careful to follow the API usage guidelines to avoid connection leaks. From the sqlx docs:
https://jmoiron.github.io/sqlx/#connectionPool
> It is easy to get into trouble by accidentally holding on to connections. To prevent this:
> 
> - Ensure you Scan() every Row object
> - Ensure you either Close() or fully-iterate via Next() every Rows object
> - Ensure every transaction returns its connection via Commit() or Rollback()
> Db API fixes

- .github/ct.yaml
So we don't have to bump the chart version every time we do changes, just for the lint to successfully run.
> charts: Don't verify the version has been bumped when linting in CI

- charts/nebraska/templates/deployment.yaml
Looks like there's an extra quote in the deployment manifest under logout url, which breaks rendering if `logoutURL` is set
when someone uses the oidc configuration
Here's what happens on `main` currently if this is set:
```
helm template  --output-dir test-output/ . --set config.auth.mode=oidc --set config.auth.oidc.logoutURL=https://my.url.com/logout --set config.auth.oidc.clientID=fake --set config.auth.oidc.clientSecret=fake 
Error: YAML parse error on nebraska/templates/deployment.yaml: error converting YAML to JSON: yaml: line 45: did not find expected '-' indicator
Use --debug flag to render out invalid YAML
```
With this typo fix:
```
helm template  --output-dir test-output/ . --set config.auth.mode=oidc --set config.auth.oidc.logoutURL=https://my.url.com/logout --set …
```
> chart: remove extra quote in logout url

- charts/nebraska/templates/deployment.yaml
Outlined in #520, while the `README.md` outlines that an `extraArgs` list is available to pass additional flags to the `nebraska` binary, it doesn't actually exist in the `deployment.yaml` manifest. This PR resolves that.
Populate `extraArgs`, and get the output templated in the `deployment.yaml` manifest as intended.
Borrowing from the example listed in [`values.yaml`](https://github.com/kinvolk/nebraska/blob/main/charts/nebraska/values.yaml#L79-L81), I tested the default chart first, which results in templates being rendered without `extraArgs` since the default is `[]`, then using the first example with:
```
helm template  --output-dir test-output/ . --set extraArgs\[0\]="-http-log"
```
resulting in the following deployment snippet being rendered:
```
args:
- "-client-title=Kinvolk …
```
> chart: add extraArgs functionality

- charts/nebraska/templates/deployment.yaml
The need for this PR is outlined in #518.
At current, if I enable the ingress without enabling the host package, all links and redirects default to `localhost`, which breaks nebraska.
The ingress by default is passed to the application through the `-nebraska-url` flag. If `.Values.config.hostFlatcarPackages.nebraskaURL` is set, it takes precedence.
I have templated locally with 
`helm template  --output-dir test-output/ . --debug`
outcome: `deployment.yaml` appends `- "-nebraska-url=http://flatcar.example.com"` to args
`helm template  --output-dir test-output/ . --set ingress.enabled=true --set ingress.hosts\[0\]="https://kinvolk.rocks"`
outcome: `deployment.yaml` appends `- "-nebraska-url=http://flatcar.example.com"`
I have installed the chart in this PR to a local cluster as well.
I am …
> chart: decouple nebraska-url flag from host packages toggle

- frontend/src/js/components/Applications/List.tsx
This is a typo fix for the default page, when no Applications are present. This usually isn't shown, but I'm seeing it with an issue with my roles, so I thought I would submit I PR. Hope this is helpful.
Shows up when no applications exist, or the user has insufficient roles.
Not sure what the stub is to run this, happy to test if necessary. Not sure how to use the typescript tool chain to run this locally.
> frontend: fix small typo to default applications message

- charts/nebraska/Chart.yaml
Can we please bump the chart so recent merges can be used?
chart version can be specified when installing the chart
> chart - update chart to 0.1.10 to include recent changes

- docs/authorization/_index.md
This patch adds a Note to setup the oidc-roles-path
argument.
> docs: Add note section to Auth0 token configuration

- .github/workflows/backend.yml
- .github/workflows/build-container.yml
- .github/workflows/frontend.yml
- .gitignore
- Makefile
- backend/.gitignore
- backend/Makefile
- frontend/.gitignore
- frontend/Makefile
- `make` will call `Makefile` in _frontend_ and _backend_
- `make run` call `run` in both _frontend_ and _backend_
- use _distroless_ for run
- use non-root user
- make binary static
- and make it smaller
- use _node_ image for frontend build
- use caching
- remove `non-cache` build parameter
- improve `.dockerignore`
- use docker/dockerfile:1.3 syntax for better caching
> chore: Split frontend and backend build parts

- backend/Makefile
- backend/docker-compose.test.yaml
- backend/go.mod
- backend/go.sum
- backend/test/api/README.md
- backend/test/api/activity_test.go
- backend/test/api/api_test.go
- backend/test/api/app_test.go
- backend/test/api/big_omaha_request.xml
- backend/test/api/channel_test.go
- backend/test/api/config_test.go
- backend/test/api/docker-compose.test.yaml
- backend/test/api/group_test.go
- backend/test/api/helper_test.go
- backend/test/api/instance_test.go
- backend/test/api/omaha_test.go
- backend/test/api/package_test.go
- backend/test/api/stats_test.go
> Add API integration tests

- .github/workflows/backend.yml
- backend/test/api/activity_test.go
- backend/test/api/app_test.go
- backend/test/api/channel_test.go
- backend/test/api/group_test.go
- backend/test/api/helper_test.go
- backend/test/api/instance_test.go
- backend/test/api/omaha_test.go
- backend/test/api/package_test.go
- backend/test/api/stats_test.go
Some lint issues slipped in because backend/test was not matched in the backend workflow.
> backend test: Fix lint issues

- charts/nebraska/Chart.lock
- charts/nebraska/Chart.yaml
- charts/nebraska/README.md
- charts/nebraska/values.yaml
Let's upgrade the postgres dependency to be in line with the current version from Bitnami.
Do you have a recommended postgres version to use together with nebraska? We could also use PG 13 or 14 if you want.
nothing special
> chart: Update postgres dependency 12.5.x -> 12.9.x

- backend/Makefile
- backend/docker-compose.test.yaml
- backend/test/api/activity_test.go
- backend/test/api/api_test.go
- backend/test/api/app_test.go
- backend/test/api/channel_test.go
- backend/test/api/config_test.go
- backend/test/api/group_test.go
- backend/test/api/instance_test.go
- backend/test/api/omaha_test.go
- backend/test/api/package_test.go
- backend/test/api/stats_test.go
- docs/development.md
You can run the dev server, and have a test db at the same time as running `make check-backend-with-container`.
1) run a test db (in docker perhaps as per dev guide `docker run --rm -d --name nebraska-postgres-dev -p 5432:5432 -e POSTGRES_PASSWORD=nebraska postgres`)
2) `make run-backend` (to show that the tests can run whilst this is running and occupying a port)
3) Now `cd backend;make check-backend-with-container` should work, and it should run the integration tests. Before there would be errors about the shared ports being used.
4) `cd backend;make check` should work as long as you have a test db running (as before). It skips the server integration tests.
5) Should be able to run a single test separately. `cd backend && make test-service-down test-service-up && cd test/api && …
> Integration test improvements

- docs/managing-updates.md
Nowadays Nebraska supports group aliases and the UUID is not needed
anymore. While the whitespace in the machine alias works for
update_engine there are some other parts in Flatcar that try to source
the update.conf file and fail when it has unqouted whitespace. Also,
the restart of update-engine.service is not really needed and it's
probably good to point the user to the Flatcar docs for more info.
> docs: update Flatcar usage section

- backend/pkg/middleware/auth.go
- backend/pkg/server/server.go
- backend/test/api/flatcar_package_test.go
- backend/test/api/helper_test.go
This patch fixes a bug that redirected the
flatcar packages request to the index.html
file.
> backend: Fix flatcar packages path bug

- Dockerfile
- Makefile
- backend/Makefile
This PR is based on the inital work by @guilhem on https://github.com/kinvolk/nebraska/pull/537. Instead of docker buildkit the docker layer caching is used for caching the dependency download on each build.
> Multistage docker build

- Dockerfile
- Makefile
- backend/Makefile
`make image` should now echo the VERSION that is used.
> Dockerfile backend: Fix VERSION not in container image

- frontend/src/js/components/Common/AutoCompletePicker.tsx
The field showing the package in the mentioned component was showing
a newly selected package (from the package selection popup) even when
the used clicked "cancel".
This patch fixes that by using a different state for setting the
mentioned value (rather than the one that reflects the user's
changes).
> frontend: Change how the package is shown in Channel/EditDialog

- backend/go.mod
- backend/go.sum
- backend/pkg/api/bindata.go
- backend/pkg/api/db/migrations/0016_add_version_breakdown_indexes.sql
- backend/pkg/api/groups.go
This patch breaks the version breakdown query
into multiple sub queries and runs them in
parallel using go routines for better
performance.
> backend: Fix Version Breakdown graph

- frontend/src/components/Packages/List.tsx
Due to how the backend changed how the items can get fetched (making
the pagination mandatory), the list of packages gotten by default was
just 10.
We should fix this by applying a real pagination in the packages'
list, but until then, this patch requests a high number of packages
so the UX is a bit better until we fix the pagination in the UI.
> frontend: Get a high number of packages until we add real pagination

- backend/docker-compose.test.yaml
- backend/pkg/server/server.go
- backend/test/api/api_secret_test.go
- backend/test/api/omaha_test.go
This is a quick PR to try to fix the issue where we can only access the update endpoint using a slash when that's being used as the endpoint secret suffix.
This PR is however incomplete: it should prevent the use of the / earlier, by letting the user know it's not allowed, and it's missing tests.
Maybe @yolossn can help complete it.
> Do not consider a slash for the endpoint secret

- frontend/src/api/API.ts
- frontend/src/components/Footer.stories.tsx
- frontend/src/components/__snapshots__/Footer.stories.storyshot
Sending an empty version is not allowed in the current API. That should be ideally prevented in the backend, but until then, this
patch removes an empty version from the query params in the respective API call.
@yolossn , I noticed that we could use an `allowEmptyValue` param for the version param and possibly others too, but the docs in swagger are not clear whether that option is going away: https://swagger.io/specification/
> frontend: Prevent sending an empty version when fetching instances

- backend/pkg/api/bindata.go
- backend/pkg/api/db/migrations/0017_drop_unused_indexes.sql
After the recent changes to improve the chart
performances this query has become redundant,
so this is removed.
> backend: Remove redundant index

- frontend/src/components/common/AutoCompletePicker/AutoCompletePicker.tsx
It was not getting correctly selected due to the "setSelected" function
not being applied to the correct value in the AutoCompletePicker.
> frontend: Fix selecting a package for a channel

- backend/pkg/handler/handler.go
The user can use the management URL to revoke access
> backend: Add management url to config

- charts/nebraska/Chart.lock
- charts/nebraska/Chart.yaml
- charts/nebraska/README.md
- charts/nebraska/values.yaml
Bitnami released a new major version of the postgresql dependency. As major chart upgrades are sometimes tricky, let's upgrade that dependency before additional majors arrive.
Nothing special.
Pushed the helm chart to my own helm repository (chartmuseum) and upgraded my nebraska instance.
> chart: Upgrade postgres dependency to latest major version

- backend/Makefile
- backend/test/api/README.md
- docs/development.md
The "docker compose" subcommand to run docker-compose does not work when "docker" is a symlink to "podman" and "docker-compose" is a symlink to "podman-compose".
Use "docker-compose" instead of the subcommand to support running with Podman and give a hint in the docs on podman-compose.
With the mentioned symlinks.
Tested `make test-service-up`
> Support Podman in docker-compose setup

- .gitignore
- backend/docker-compose.pg-persist.yaml
- backend/docker-compose.test.yaml
This change adds a dependency to the (nebraska) "server" service on the "postgres" service in docker-compose.test.yaml. Motivation of the change is to prevent a race condition where the "server" container starts faster than "postgres", fails to connect to the database, and shuts down.
Additionally, an optional persistent storage for postgres is added. DB contents can be persisted across docker-compose runs to aid manual, interactive testing. Usage instructions have been added to the YAML files as comments. The local directory used for persiting postgres data has been added to .gitignore to prevent accidental commits.
Tested locally with:
- `docker-compose --file docker-compose.test.yaml build`  (works as expected)
- `docker-compose --file docker-compose.test.yaml up` (works as expected)
- …
> backend/docker-compose: remove race condition and improve interactive dev experience

- Makefile
- backend/Makefile
The userctl command got removed in summer 2021 but was still part of the first run of "make" in a fresh checkout.
> backend/Makefile: Remove unused userctl reference

- docs/authorization/_index.md
The images on the `authorization` docs page are currently not displayed, due to the wrong src path.
Visit the current `authorization` docs page: https://kinvolk.io/docs/nebraska/latest/authorization/ to see that they are currently broken.
I changed the `/./` to `/../` for the image src paths via `Inspect Element` on the current docs page (https://kinvolk.io/docs/nebraska/latest/authorization/) to check if the changes work currently.
> docs: Fix image url paths

- backend/pkg/api/bindata.go
- backend/pkg/api/db/migrations/0019_add_instance_stats_table.sql
- backend/pkg/api/instances.go
- backend/pkg/api/instances_test.go
A by-product of the Omaha update protocol employed by Nebraska delivers statistics on version spread, but accumulating and presenting this data suffers from a number of limitations:
-	The chart only represents all nodes’ current OS versions. We currently do not have historic data of the nodes’ previous software versions, and we would like to track of this data.
-	While historic data can be calculated from update events, this is computationally intense and unfeasible in practice. We currently cannot calculate or store this historic data efficiently, and we would like to be able to have quick and easy access to this data.
-	To be able to back-fill the live Nebraska server using historic data available in CSV format, we need to use a third-party tool. We currently cannot accomplish this …
> Add instance statistics table

- backend/pkg/api/instances.go
The time.Now() function uses the local time which causes a mismatch and no entries get created when, e.g., being two hours ahead because the instance would be checking in at 10 UTC but it gets compared to 12 local time and in this time span nothing is able to check in because the local time will always be too far ahead.
Use the right time zone for the default time of the instance stats query.
Checked whether entries get created:
```
psql postgres://postgres:nebraska@localhost:5432/nebraska -c "select * from instance_stats;"
```
> backend: Use UTC for instance stats default time

- backend/pkg/api/instances.go
- backend/pkg/api/instances_test.go
- backend/pkg/server/server.go
Following #656 where we add the `instance_stats` table, we now implement a background task that populates this table every hour, with the purpose of committing a snapshot of live instance counts to the new database table. This task, using a Go ticker, is started at service startup and runs for the whole lifetime of the Nebraska server until it is stopped.
> Add instance_stats background job

- backend/pkg/api/instances.go
- backend/pkg/server/server.go
Following #663 where we add the background job to periodically populate the `instance_stats` table, we want to ensure that we generate entries for instances that may not check in hourly but are still active. Thus, we consider a 2-hour default interval for instances checking in, maintaining the hourly cadence of the background job as desired.
> backend: Change default interval for instance stats query

- dependabot.yml
The config file seems to be needed now. It's also useful to limit the PRs in-flight with "open-pull-requests-limit: 0" if we get too many PRs at once.
Suggested by @mkilchhofer
> dependabot: Add required config file

- .github/workflows/helm-chart-lint-test.yaml
- .github/workflows/helm-chart-release.yml
I contributed the helm chart (https://github.com/flatcar/nebraska/pull/330) and the actions almost 2,5+ years ago and now it is time to update all actions related to produce and test the helm chart.
As I also maintain the Argo helm project, most updates are validated against the settings used over there:
- Chart testing: https://github.com/argoproj/argo-helm/blob/main/.github/workflows/lint-and-test.yml
- Chart releasing: https://github.com/argoproj/argo-helm/blob/main/.github/workflows/publish.yml
n/a
Tested both workflow updates in my fork repo:
- chart releasing: https://github.com/mkilchhofer/nebraska/actions/runs/7172293969
- chart testing: https://github.com/mkilchhofer/nebraska/actions/runs/7171035624
> chore: Update all actions related to the helm chart

- .github/workflows/backend.yml
- .github/workflows/build-container.yml
- .github/workflows/frontend.yml
In my last PR(s), I updated the helm specific actions:
- https://github.com/flatcar/nebraska/pull/675
- https://github.com/flatcar/nebraska/pull/697
Now since dependabot can also update the actions (https://github.com/flatcar/nebraska/pull/676 / https://github.com/flatcar/nebraska/pull/685), we can pin all other actions too.
Dependabot will update the actions in the future. Example PR from my other maintainer work over there:
- https://github.com/argoproj/argo-helm/pull/2382
Tested all 3 actions "manually" in my forked repo with this PR here:
- https://github.com/mkilchhofer/nebraska/pull/26
> ![image](https://github.com/flatcar/nebraska/assets/7290987/2bf1e440-744e-452d-ba4f-725296d28d0f)
Detailed action logs:
- frontend: https://github.com/mkilchhofer/nebraska/actions/runs/7187152180/job …
> chore: Update and pin all actions

- Makefile
- backend/Makefile
It seems that the versioning gets confused by the helm releases also produces git tags.
Before this change:
After:
`-`
See screenshots above
> fix: Exclude helm chart tags from appVersion calculation

- .github/workflows/updater.yml
I observed that the PRs for `/updater` were not automatically tested with GH actions. Updater library was introduced here by @joaquimrocha :
- https://github.com/flatcar/nebraska/pull/460
nothing special
Merged this PR on my forks `main` branch and filed a PR with one of the open PRs here:
- https://github.com/mkilchhofer/nebraska/pull/27
Action output: https://github.com/mkilchhofer/nebraska/actions/runs/7380534949/job/20078013657?pr=27
> feat: Test updater library

- backend/pkg/util/log.go
Fixes #715 
```log
<nil> DBG Unknown format context=api logFormat=
<nil> DBG Unknown format context=nebraska logFormat=
<nil> DBG Unknown format context=auth logFormat=
<nil> DBG Unknown format context=omaha logFormat=
<nil> DBG Unknown format context=nebraska logFormat=
<nil> DBG Unknown format context=nebraska logFormat=
<nil> DBG Unknown format context=syncer logFormat=
____    __
/ __/___/ /  ___
/ _// __/ _ \/ _ \
/___/\__/_//_/\___/ v4.10.2
High performance, minimalist Go web framework
https://echo.labstack.com
____________________________________O/_______
O\
⇨ http server started on [::]:8000
```
```log
<nil> DBG Unknown format context=api logFormat=pretty
<nil> DBG Unknown format context=nebraska logFormat=pretty
<nil> DBG Unknown format context=auth logFormat=pretty
<nil> DBG …
```
> fix: Get rid of the <nil> fields in all log outputs

- .github/workflows/release-container.yml
When creating a release tag we want the image to be built and published
as flatcar/nebraska with the version tag and also as 'latest' image when
the tag is not the special 'staging' tag.
The nebraska-helm chart is also released on the same repo, and thus we
need to filter for strict semver tags.
Maybe we need to iterate over this a bit more in the course of the new release until it publishes things correctly.
> .github: Add GitHub Action to release container image

- backend/pkg/auth/oidc.go
Change the refresh token behaviour so that the refresh token is only deemed necessary when the access token has expired. If it is not supplied but the access token has not expired then we will no longer fail validation.
Gain an id_token and refresh_token from OIDC, supply only the id_token in the Bearer auth header to Nebraska. This will work, whereas previously it did not.
Used `dex` with an LDAP connector and local user authentication, with group support added (https://github.com/mjudeikis/dex/tree/mjudeikis/groups.support). Tested OIDC authentication in browser through Dex with LDAP user, confirmed working. Tested OIDC authentication in `curl` through Dex with local user, confirmed working. The `curl` commands were similar to:
```
curl -L -X POST 'http://localhost:5556/dex/token' \
-H …
```
> Only Require OIDC Refresh Token If Access Token Expired

- backend/pkg/config/config.go
- backend/test/auth/oidc/auth_test.go
The backend expects refresh tokens, however they have to be requested for the token exchange with special scope
The Nebraska backend expects refresh tokens for the Nebraska use sessions with the Nebraska frontend, however the refresh token is not acquired with the default configuration as it has to be requested by using the special scope `offline_access`.
You can remove the `offline_access` scope overriding the default config with the flag `--oidc-scopes`, for example `--oidc-scopes openid`.
1. Set up an IDP
2. use the oidc authentication method
3. ensure that the `offline_access` scope is provided along with `openid` when Nebraska initiates the authentication flow
4. ensure the idp issues refresh tokens
5. set the access token expiration to a low value to easily verify if the bakcend can …
> backend: default oidc scopes list

- backend/docker-compose.test.yaml
- backend/pkg/sessions/session.go
- frontend/src/components/Channels/ChannelEdit.tsx
See: https://github.com/flatcar/nebraska/issues/901
Run the stack locally with oidc auth mode:
```sh
air --build.cmd "go build -o ./bin/nebraska ./cmd/nebraska/main.go" \
--build.bin "./bin/nebraska" \
--build.args_bin "\
-debug \
--auth-mode oidc \
--oidc-admin-roles nebraska_admin \
--oidc-viewer-roles nebraska_member \
--oidc-roles-path \"http://kinvolk\.io/roles\" \
--oidc-client-id [redacted]\
--oidc-issuer-url https://[redacted].com/ \
--oidc-client-secret [redacted] \
-oidc-valid-redirect-urls http://localhost:3000/*"
```
Obeserve that the oidc cookie has the httponly flag after login:
> Fix/901 OIDC cookie http only

- .github/workflows/scorecard-analysis.yml
- README.md
- CI: scorecard-analysis: Add config for OpenSSF scorecard
- README: Add OpenSSF scorecard badge
This is required for CNCF projects at the incubated stage.
Additionally, once merged it gives more code scanning results in the Security tab -> Code Scanning section on github.
https://github.com/flatcar/nebraska/security/code-scanning
Once merged click on the badge in the README.
Note, `flatcar/nebraska` isn't already scanned by OpenSSF, so it does not have data for it yet. To get the data, the action will have to be run manually the first time, OR wait for the badge results to be updated once daily. The action is run daily via github action cron.
We use it in the headlamp/inspektor gadget repos, and it uses the OpenSSF template for the workflow.
> CI: README: Add OpenSSF scorecard badge

- charts/nebraska/Chart.yaml
https://github.com/flatcar/nebraska/releases/tag/2.10.0
> release(helm): bump app to v2.10.0 and charts to v1.3.0 charts
