flatcar/nebraska

frontend/src/js/components/Applications/ApplicationItemChannelsList.react.js
frontend/src/js/components/Applications/ApplicationItemGroupsList.react.js
frontend/src/js/components/Channels/Item.react.js
frontend/src/js/components/Common/Card.js
frontend/src/js/components/Common/MoreMenu.js
frontend/src/js/components/Common/VersionBreakdownBar.js
frontend/src/js/components/Groups/Item.react.js
frontend/src/js/components/Groups/ItemExtended.react.js
frontend/src/js/components/Instances/Details.js
frontend/src/js/components/Layouts/MainLayout.react.js
frontend/src/js/components/Packages/Item.react.js

I went through (hopefully) all the errors/warnings in the js console and fixed them.

Fix warnings

---

cmd/nebraska/controller.go
go.mod
go.sum
pkg/api/packages.go
pkg/omaha/omaha.go
pkg/omaha/omaha_test.go
pkg/syncer/syncer.go

The updated packages are mostly the "quick wins" ones. What's left is to update is web framework, database ORM and logging. The last two are kinda coupled since the ORM we use currently is using the current logger used in nebraska.

Update some packages

---

tools/check_pkg_test.sh

This is to address an issue raised in #108.

tools: Explain what check_pkg_test.sh script is doing

---

frontend/src/js/components/Channels/ChannelAvatar.js
frontend/src/js/components/Channels/EditDialog.js
frontend/src/js/components/Channels/Item.react.js
frontend/src/js/components/Packages/EditDialog.js
frontend/src/js/components/Packages/Item.react.js
frontend/src/js/constants/helpers.js

This PR adds the new architecture information of packages and channels to the UI.

Add architecture information to the UI

---

pkg/api/groups.go

In a recent change to filter undesired IDs from the version count
timeline a syntax mistake was left undetected (an AND was forgotten
between WHERE member clauses).

backend: Fix syntax issue in version count timeline SQL

---

frontend/src/js/components/Groups/Charts.js

fixed typo in  Version Breakdown chart 

---

frontend/src/js/components/Activity/Container.react.js

Pagination fix for activity list

---

frontend/src/js/components/Channels/List.react.js

Fix architecture sticky behaviour in channel list

---

frontend/src/js/components/Groups/EditDialog.js

Fix Style of Channels/List to group architectures in Edit Group

---

cmd/nebraska/controller.go
pkg/syncer/syncer.go

This PR includes the code added in #152 but with an improvement of the commit message, as well as a new commit that adds a more future-proof fix.

Fix updates URL

---

frontend/.eslintrc.yml
frontend/src/js/api/API.js
frontend/src/js/components/Applications/List.react.js
frontend/src/js/components/Channels/Item.react.js
frontend/src/js/components/Channels/List.react.js
frontend/src/js/components/Common/Card.js
frontend/src/js/components/Common/ColorPicker.js
frontend/src/js/components/Common/SectionHeader.js
frontend/src/js/components/Groups/Charts.js
frontend/src/js/components/Groups/EditDialog.js
frontend/src/js/components/Groups/List.react.js
frontend/src/js/components/Instances/Charts.js
frontend/src/js/components/Instances/Details.js
frontend/src/js/components/Instances/List.js
frontend/src/js/components/Layouts/InstanceLayout.js
frontend/src/js/constants/helpers.js
frontend/src/js/stores/InstancesStore.js

Another couple of rules which I think should be added to the linter.

Spaces linter

---

frontend/.eslintrc.yml
frontend/src/js/components/Activity/Item.react.js
frontend/src/js/components/Applications/List.react.js
frontend/src/js/components/Channels/List.react.js
frontend/src/js/components/Groups/Charts.js
frontend/src/js/components/Groups/EditDialog.js
frontend/src/js/components/Groups/Item.react.js
frontend/src/js/components/Groups/ItemExtended.react.js
frontend/src/js/components/Groups/List.react.js
frontend/src/js/components/Instances/Details.js
frontend/src/js/components/Instances/Item.react.js
frontend/src/js/components/Instances/List.js
frontend/src/js/components/Instances/StatusHistoryContainer.react.js
frontend/src/js/components/Instances/StatusHistoryItem.react.js
frontend/src/js/components/Layouts/GroupLayout.react.js
frontend/src/js/components/Layouts/InstanceLayout.js
frontend/src/js/components/Layouts/InstanceListLayout.js
frontend/src/js/components/Packages/EditDialog.js
frontend/src/js/constants/regex.js
frontend/src/js/stores/ApplicationsStore.js
frontend/src/js/stores/InstancesStore.js

We should keep the line length consistent across the project. So this
patch adds that rule to the frontend's linter.

frontend: Add maximum line length linter rule

---

frontend/.eslintrc.yml
frontend/src/js/components/Layouts/InstanceLayout.js

Another rule to make things consistent.

Arrow functions lint

---

frontend/src/js/components/Instances/List.js

Add filter and pagination to url

---

pkg/api/updates.go
pkg/api/updates_test.go

When the fast path was added to re-grant an update that was already
granted (6bcd6fdbfd2d7ad29b17ab830219ed1aad34be1a) this skipped the
version check, resulting in granting an update to clients that already
run this version. The DB state of granting an update should not be
more important than the version of the instance because the DB can either
lack entries (due to the client not sending them or the server dropping
them) or it can also be tricked by a malicious third party pretending
to be the client but with a lower app version.
Only re-grant an update after performing all checks that are normally
done as well, i.e., if the client's version needs an update and if the
package wasn't forbidden for this channel in the mean time. Set the
instance status to InstanceStatusComplete to keep the …

backend: Grant update only after checking the version

---

pkg/api/updates_test.go

At least on my machine the tests started to fail because of timing
issues and it was also observed before.
Make the timing more robust by using 500 instead of 100/200
milliseconds because they were already reached by simple function
calls, causing the update timeout being hit instead of just entering
the next period interval.

backend: Make test timing more robust and explain it

---

frontend/src/js/components/Channels/Item.react.js
frontend/src/js/components/Packages/Item.react.js

This PR fixes the date formatting for channels and packages.

Date formatting

---

frontend/src/js/components/Footer.js
frontend/src/js/components/Main.react.js

Add nebraska version in ui

---

pkg/api/packages.go
pkg/api/packages_test.go

Fix upsert query for flatcar action

---

frontend/package-lock.json
frontend/package.json

This comes as a result of running audit fix + updating a couple of
dependencies manually.

frontend: Bump some of the dependencies

---

cmd/nebraska/nebraska.go

Signed-off-by: Vincent Batts <vbatts@kinvolk.io>

cmd/nebraska: useless use of Sprintf

---

frontend/src/js/components/Common/TimeIntervalLinks.js
frontend/src/js/components/Groups/ItemExtended.react.js
frontend/src/js/components/Instances/List.js

Times on instances list

---

pkg/api/api.go

Adds password to default database URL.

backend: Fix default database URL

---

frontend/src/js/components/Channels/List.react.js

Fixes: https://github.com/kinvolk/nebraska/issues/318

frontend: Add null check to ChannelList

---

cmd/nebraska/controller.go

Allow More forgiving X-Forwarded-For handling

---

cmd/nebraska/auth/githubauth.go

Right now setting the accesslevel sets the value without
checking if the value already exists, this leads to ro
overwriting rw accesslevel. A check is added to prevent it.
Signed-off-by: yolossn <santhosh@kinvolk.io>
fixes #335

backend: Fix overwriting of accesslevel in github auth

---

cmd/nebraska/auth/githubauth.go

Right now if the user is added to the rw team the
active sessions are not deleted and the access level
remains same. The fix handles the added github
webhook event and drops all the active sessions of
the user.
Signed-off-by: yolossn <santhosh@kinvolk.io>

backend: Drop all user sessions on gh team addition

---

frontend/src/js/components/Instances/StatusHistoryItem.tsx

 Fix status render for StatusHistoryItem view

---

go.mod
go.sum
pkg/omaha/omaha.go
pkg/omaha/omaha_test.go
pkg/syncer/syncer.go
updaters/lib/go/helpers.go

depends on https://github.com/kinvolk/go-omaha/pull/5
Signed-off-by: Vincent Batts <vbatts@kinvolk.io>

*.go: repoint go-omaha to kinvolk fork

---

cmd/nebraska/auth/auth.go
cmd/nebraska/nebraska.go
pkg/api/api.go
pkg/api/events.go
pkg/omaha/omaha.go
pkg/syncer/syncer.go
pkg/util/log.go

- backend: Support logging in JSON
- backend: Downgrade a coulpe of omaha related logs from warn to debug
- backend: Don't log an error when registering an event for a new instance

Improve logging for regular pings

---

charts/nebraska/Chart.yaml

Nebraska to 2.3.5, Chart to 0.1.4.

chart: Bump chart and its Nebraska versions

---

docs/authorization.md

Add docs for howto using the helm chart contributed in #330.

docs: Add basic Kubernetes deployment instructions

---

docs/development.md

Fix Broken Link to Frontend Project mentioned at development guidelines

development.md: Update broken link to frontend

---

Makefile

Run make run-backend after building the backend and it should start the backend server
Yes

backend: Fix make target for running backend

---

backend/cmd/nebraska/auth/oidcauth.go
backend/cmd/nebraska/nebraska.go

this patch fixes the CI errors which were
introduced by the OIDC feature

backend: Fix CI Errors

---

frontend/src/js/api/API.ts
frontend/src/js/stores/redux/features/config/index.ts

frontend: Fix nebraska_config parsing

---

docs/authorization.md

This patch adds documentation for setting up
Dex with Github connection as OIDC provider.

docs: Add Dex IDP setup for OIDC

---

backend/cmd/nebraska/controller.go
backend/pkg/api/instances.go
frontend/src/js/components/Instances/List.tsx
frontend/src/js/components/Instances/Table.tsx
frontend/src/js/utils/helpers.ts

Adds sort filter to instances list
Go to instance list view and apply the various sort filters available, also use the sortOrder filter to change in what order you want the sorted data to appear(desc or asc)
Yes

Add sort to instance list

---

frontend/src/js/components/Instances/List.tsx
frontend/src/js/components/Instances/Table.tsx

- frontend: Set arrow-up/down as asc/desc order in Instances/Table
- frontend: Add the swap icon to sort buttons in not-sorted columns
- frontend: Use asc/desc names for the sort order instead of a boolean
- frontend: Sort instances list from most recent ping to least recent

Improve instances sorting

---

frontend/package-lock.json
frontend/package.json
frontend/src/index.tsx

Add [@axe-core/react](https://github.com/dequelabs/axe-core-npm/tree/develop/packages/react) to log a11y issues in the console.
See the js dev console whenever react state changes - it should show automatically found issues.

Add @axe-core/react to console.log a11y issues

---

.github/workflows/helm-chart-lint-test.yaml
.github/workflows/helm-chart-release.yml
charts/nebraska/Chart.yaml
charts/nebraska/README.md
charts/nebraska/templates/deployment.yaml
charts/nebraska/templates/secrets.yaml
charts/nebraska/values.yaml

This patch adds changes to the helm chart to support
oidc auth mode.

chart: Add OIDC auth mode support to helm chart

---

.github/workflows/build-container.yml
Dockerfile

- Dockerfile: Build the backend binary without generating changes
- .github: Run build-container action if Dockerfile is touched

Build simple binary on images

---

frontend/src/js/__tests__/Applications/__snapshots__/Item.spec.js.snap
frontend/src/js/__tests__/Applications/__snapshots__/List.spec.js.snap
frontend/src/js/__tests__/Common/ListItem.spec.js
frontend/src/js/components/Channels/List.tsx
frontend/src/js/components/Common/Card.tsx
frontend/src/js/components/Common/ListHeader.tsx
frontend/src/js/components/Common/ListItem.tsx
frontend/src/js/components/Common/MoreMenu.tsx
frontend/src/js/components/Groups/Item.tsx
frontend/src/js/components/Layouts/ApplicationLayout.tsx
frontend/src/js/components/Layouts/MainLayout.tsx
frontend/src/js/components/Main..tsx
frontend/src/js/i18n/LocaleSelect/LocaleSelect.tsx
frontend/src/js/i18n/ThemeProviderNexti18n.tsx

A third round of improvements.
Using the tools: WAVE, and firefox accessibility tab and a checklist found some more issues.

Some accessibility improvements

---

frontend/src/js/components/Common/PageTitle.tsx
frontend/src/js/components/Common/SectionHeader.tsx

Setting the document title is useful for helping people know what page they are on.
related: https://github.com/kinvolk/nebraska/issues/363

Add title change when changing page

---

.github/workflows/backend.yml

See other PRs are not running backend CI checks even when the backend has been changed.

github: Enable workflows/backend.yml again

---

backend/pkg/api/users.go
backend/pkg/api/users_test.go

There is also an AddUser bugfix.
```
go test -v ./pkg/api/ '-run=^TestAddUser$'
go test -v ./pkg/api/ '-run=^TestGetUsersInTeam$'
```

backend/pkg/api/users tests, and a bug fix

---

backend/pkg/api/channels.go
backend/pkg/api/packages.go
backend/pkg/api/packages_test.go

- simplified a check in packages.AddPackage
- added a test for the check

backend packages: Simplify check of channel arch in AddPackage

---

frontend/src/js/components/Channels/List.tsx
frontend/src/js/components/Groups/EditDialog/index.tsx
frontend/src/js/components/Groups/Item.tsx
frontend/src/js/components/Packages/List.tsx

- frontend: Add a description for when the channels list is empty
- frontend: Fix setting the group's update per period
- frontend: Add a space between the channel's label and its contents
- frontend: Ensure that packages will show up in the list after created

Fix adding groups

---

frontend/src/js/api/API.ts
frontend/src/js/api/apiDataTypes.ts
frontend/src/js/components/Common/ConfirmationContent.tsx
frontend/src/js/components/Instances/Details.tsx
frontend/src/js/components/Instances/List.tsx
frontend/src/js/components/Instances/StatusHistoryItem.tsx
frontend/src/js/components/Packages/EditDialog.tsx
frontend/src/js/stores/ApplicationsStore.ts
frontend/src/js/utils/helpers.ts

Adding types to the API means that they flow through to the rest of the app and allow better checking.
It's a start on https://github.com/kinvolk/nebraska/issues/451
App should behave as before, but also type-check.
Ran `npm run tsc` and the tests.

frontend: Improve API types

---

backend/cmd/nebraska/controller.go
backend/pkg/api/instances.go
backend/pkg/api/instances_test.go
frontend/src/js/__tests__/Common/__snapshots__/ListSearch.spec.js.snap
frontend/src/js/components/Common/LightTooltip.tsx
frontend/src/js/components/Common/ListSearch.tsx
frontend/src/js/components/Instances/Charts.tsx
frontend/src/js/components/Instances/List.tsx
frontend/src/js/utils/helpers.ts

Port instance fetching query to a join query
Go to instance list view and try using filters and pagination to see whether the current approach of getting instance works and is similarly fast as the earlier approach
##Features
**Search without classifier**
**Search With classifier**

backend: Change instance fetch query to a join query & add search

---

frontend/src/js/api/apiDataTypes.ts
frontend/src/js/components/Applications/EditDialog.tsx
frontend/src/js/components/Channels/List.tsx
frontend/src/js/components/Groups/EditDialog/GroupDetailsForm.tsx
frontend/src/js/components/Groups/Item.tsx
frontend/src/js/components/Groups/ItemExtended.tsx
frontend/src/js/components/Layouts/InstanceLayout.tsx
frontend/src/js/components/Layouts/InstanceListLayout.tsx
frontend/src/js/components/Packages/EditDialog.tsx
frontend/src/js/stores/ApplicationsStore.ts

- frontend: Add missing "packages" field to the Application interface
- frontend: Complete some missing type information in several components
- frontend: Show an up to date list of packages when assigning a channel
- frontend: Check if version_breakdown is valid before using its length
- frontend: Reflect package creation's result in the new package form
- frontend: Use "applications" as the ns for apps' translations
- frontend: Make "Channels" in the GroupDetailsForm translatable

Small UI improvements

---

Makefile

- Makefile: Tag image as ghcr.io/kinvolk/nebraska
- Makefile: Rename container-nebraska target as image

Move default image repo to ghcr.io

---

frontend/src/js/components/Groups/EditDialog/GroupDetailsForm.tsx
frontend/src/js/components/Groups/EditDialog/GroupPolicyForm.tsx
frontend/src/js/components/Groups/EditDialog/index.tsx

Go to group edit view and try invalidating a field and you will be shown with the validation errors

Fix group edit validations

---

frontend/src/js/components/Packages/EditDialog.tsx

For https://github.com/kinvolk/nebraska/issues/485
Add a flatcar package with metadata fields, then edit the metadata fields.

Add metadata fields to Flatcar package types

---

frontend/src/js/components/Groups/EditDialog/GroupDetailsForm.tsx
frontend/src/js/components/Groups/EditDialog/index.tsx

Closes https://github.com/kinvolk/nebraska/issues/488 and https://github.com/kinvolk/nebraska/issues/476

frontend: Fix group channel editing

---

Makefile
backend/tools/setup_local_db.sh

Makefile, backend: Fix pg-version pin

Makefile, backend: Fix pg-version pin

---

docs/authorization/_index.md
docs/authorization/autovacuum-tune.sql

This is what we've agreed as the next step for the psql autovacuum settings.
We should close #508 once this is accepted.

docs: Add new subsection about Postgres autovacuum tuning

---

backend/docker-compose.test.yaml
docs/development.md

-    backend: Fix make check-backend-with-container(Was failing for me with an alpine download error)
-    docs: Add note about docker compose V2

Check backend with container network issue, document docker compose

---

frontend/src/__tests__/Common/ModalButton.spec.js
frontend/src/components/Groups/GroupEditDialog/GroupEditDialog.tsx

1. Click on an application.
2. Click on a group.
3. Editing the group should work.

frontend: Fix undefined appId breaking group edit

---

docs/development.md

The most parts are automated now and it should be easy to cut a new release as long as the instructions are in place.

docs: Document how Nebraska releases work

---

MAINTAINERS.md

See https://github.com/flatcar/Flatcar/pull/1619

MAINTAINERS.md: Add Ervin as Nebraska maintainer

---

Dockerfile

* used upper case latters in the FROM * AS expressions
* Use the new key value pair syntax
Image builds.

style(ci): standardize Dockerfile syntax

---

CHANGELOG.md

https://keepachangelog.com/en/1.0.0/

feat(changelog): add initial CHANGELOG.md file

---

CHANGELOG.md

changelog: add release 2.10.0
